# Generated by Django 4.2.11 on 2024-06-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0072_rename_eshippersettings_eshipperxmlsettings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NinjaVanSettings",
            fields=[
                (
                    "carrier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="providers.carrier",
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                (
                    "grant_type",
                    models.CharField(default="client_credentials", max_length=255),
                ),
            ],
            options={
                "verbose_name": "NinjaVan Settings",
                "verbose_name_plural": "NinjaVan Settings",
                "db_table": "ninjavan_settings",
            },
            bases=("providers.carrier",),
        ),
    ]
